#SingleInstance force
retardo = 50
SetKeyDelay, 20
^d::
Send, MediaMarkt{enter}
Sleep %retardo%
Send, S{enter}
Sleep %retardo%
Send, Impresora{enter}
Sleep %retardo%
Send, 395.69{enter}
Sleep %retardo%
Send, 102.64{enter}
Sleep %retardo%
Send, 387.93{enter}
Sleep %retardo%
Send, Televisor{enter}
Sleep %retardo%
Send, 123.68{enter}
Sleep %retardo%
Send, 114.13{enter}
Sleep %retardo%
Send, 116.21{enter}
Sleep %retardo%
Send, Smartwatch{enter}
Sleep %retardo%
Send, 408.15{enter}
Sleep %retardo%
Send, 407.36{enter}
Sleep %retardo%
Send, 417.84{enter}
Sleep %retardo%
Send, fin{enter}
Sleep %retardo%
Send, Fnac{enter}
Sleep %retardo%
Send, N{enter}
Sleep %retardo%
Send, Accesorio{enter}
Sleep %retardo%
Send, 110.90{enter}
Sleep %retardo%
Send, 105.16{enter}
Sleep %retardo%
Send, 107.22{enter}
Sleep %retardo%
Send, Drone{enter}
Sleep %retardo%
Send, 173.70{enter}
Sleep %retardo%
Send, 171.15{enter}
Sleep %retardo%
Send, 176.84{enter}
Sleep %retardo%
Send, fin{enter}
Sleep %retardo%
Send, PcComponentes{enter}
Sleep %retardo%
Send, N{enter}
Sleep %retardo%
Send, Gaming{enter}
Sleep %retardo%
Send, 448.16{enter}
Sleep %retardo%
Send, 453.24{enter}
Sleep %retardo%
Send, 449.56{enter}
Sleep %retardo%
Send, Altavoz{enter}
Sleep %retardo%
Send, 475.59{enter}
Sleep %retardo%
Send, 466.49{enter}
Sleep %retardo%
Send, 473.92{enter}
Sleep %retardo%
Send, Periférico{enter}
Sleep %retardo%
Send, 434.99{enter}
Sleep %retardo%
Send, 427.18{enter}
Sleep %retardo%
Send, 439.62{enter}
Sleep %retardo%
Send, Teléfono{enter}
Sleep %retardo%
Send, 240.15{enter}
Sleep %retardo%
Send, 230.82{enter}
Sleep %retardo%
Send, 248.56{enter}
Sleep %retardo%
Send, Portátil{enter}
Sleep %retardo%
Send, 342.06{enter}
Sleep %retardo%
Send, 351.52{enter}
Sleep %retardo%
Send, 338.75{enter}
Sleep %retardo%
Send, fin{enter}
Sleep %retardo%
Send, Apple{enter}
Sleep %retardo%
Send, S{enter}
Sleep %retardo%
Send, Teléfono{enter}
Sleep %retardo%
Send, 118.95{enter}
Sleep %retardo%
Send, 126.07{enter}
Sleep %retardo%
Send, 117.57{enter}
Sleep %retardo%
Send, Gaming{enter}
Sleep %retardo%
Send, 168.19{enter}
Sleep %retardo%
Send, 176.76{enter}
Sleep %retardo%
Send, 176.11{enter}
Sleep %retardo%
Send, Accesorio{enter}
Sleep %retardo%
Send, 363.67{enter}
Sleep %retardo%
Send, 366.56{enter}
Sleep %retardo%
Send, 369.51{enter}
Sleep %retardo%
Send, fin{enter}
Sleep %retardo%
Send, Xiaomi{enter}
Sleep %retardo%
Send, N{enter}
Sleep %retardo%
Send, Portátil{enter}
Sleep %retardo%
Send, 322.31{enter}
Sleep %retardo%
Send, 316.80{enter}
Sleep %retardo%
Send, 322.06{enter}
Sleep %retardo%
Send, Accesorio{enter}
Sleep %retardo%
Send, 145.77{enter}
Sleep %retardo%
Send, 150.44{enter}
Sleep %retardo%
Send, 146.21{enter}
Sleep %retardo%
Send, Smartwatch{enter}
Sleep %retardo%
Send, 456.40{enter}
Sleep %retardo%
Send, 464.94{enter}
Sleep %retardo%
Send, 447.88{enter}
Sleep %retardo%
Send, Cámara{enter}
Sleep %retardo%
Send, 114.71{enter}
Sleep %retardo%
Send, 112.75{enter}
Sleep %retardo%
Send, 117.44{enter}
Sleep %retardo%
Send, fin{enter}
Sleep %retardo%
Send, Worten{enter}
Sleep %retardo%
Send, N{enter}
Sleep %retardo%
Send, Tableta{enter}
Sleep %retardo%
Send, 210.61{enter}
Sleep %retardo%
Send, 208.40{enter}
Sleep %retardo%
Send, 213.09{enter}
Sleep %retardo%
Send, Domótica{enter}
Sleep %retardo%
Send, 189.19{enter}
Sleep %retardo%
Send, 190.31{enter}
Sleep %retardo%
Send, 184.57{enter}
Sleep %retardo%
Send, Drone{enter}
Sleep %retardo%
Send, 280.77{enter}
Sleep %retardo%
Send, 276.65{enter}
Sleep %retardo%
Send, 274.46{enter}
Sleep %retardo%
Send, Smartwatch{enter}
Sleep %retardo%
Send, 265.90{enter}
Sleep %retardo%
Send, 269.96{enter}
Sleep %retardo%
Send, 258.67{enter}
Sleep %retardo%
Send, fin{enter}
Sleep %retardo%
Send, Phonehouse{enter}
Sleep %retardo%
Send, S{enter}
Sleep %retardo%
Send, Monitor{enter}
Sleep %retardo%
Send, 345.12{enter}
Sleep %retardo%
Send, 350.13{enter}
Sleep %retardo%
Send, 342.70{enter}
Sleep %retardo%
Send, Impresora{enter}
Sleep %retardo%
Send, 220.63{enter}
Sleep %retardo%
Send, 216.04{enter}
Sleep %retardo%
Send, 218.87{enter}
Sleep %retardo%
Send, Periférico{enter}
Sleep %retardo%
Send, 259.86{enter}
Sleep %retardo%
Send, 265.30{enter}
Sleep %retardo%
Send, 259.61{enter}
Sleep %retardo%
Send, Almacenamiento{enter}
Sleep %retardo%
Send, 392.79{enter}
Sleep %retardo%
Send, 402.09{enter}
Sleep %retardo%
Send, 384.12{enter}
Sleep %retardo%
Send, fin{enter}
Sleep %retardo%
Send, Webuy{enter}
Sleep %retardo%
Send, S{enter}
Sleep %retardo%
Send, Domótica{enter}
Sleep %retardo%
Send, 485.12{enter}
Sleep %retardo%
Send, 487.15{enter}
Sleep %retardo%
Send, 487.20{enter}
Sleep %retardo%
Send, Proyector{enter}
Sleep %retardo%
Send, 314.42{enter}
Sleep %retardo%
Send, 306.91{enter}
Sleep %retardo%
Send, 311.90{enter}
Sleep %retardo%
Send, Periférico{enter}
Sleep %retardo%
Send, 192.78{enter}
Sleep %retardo%
Send, 183.63{enter}
Sleep %retardo%
Send, 197.16{enter}
Sleep %retardo%
Send, fin{enter}
Sleep %retardo%
Send, fin{enter}
Sleep %retardo%