retardo = 300

^d::
Send, AB653{enter}
Sleep %retardo%

Send, 3{enter}
Sleep %retardo%
Send, 7646DKL{enter}
Sleep %retardo%
Send, G{enter}
Sleep %retardo%
Send, 1200{enter}
Sleep %retardo%
Send, 30000{enter}
Sleep %retardo%
Send, 6530CWS{enter}
Sleep %retardo%
Send, D{enter}
Sleep %retardo%
Send, 1400{enter}
Sleep %retardo%
Send, 40000{enter}
Sleep %retardo%
Send, 5246FRS{enter}
Sleep %retardo%
Send, D{enter}
Sleep %retardo%
Send, 2000{enter}
Sleep %retardo%
Send, 45700{enter}
Sleep %retardo%

Send, HB876{enter}
Sleep %retardo%

Send, 5{enter}
Sleep %retardo%
Send, 6547HRP{enter}
Sleep %retardo%
Send, G{enter}
Sleep %retardo%
Send, 2200{enter}
Sleep %retardo%
Send, 32402{enter}
Sleep %retardo%
Send, 3948BSR{enter}
Sleep %retardo%
Send, G{enter}
Sleep %retardo%
Send, 3000{enter}
Sleep %retardo%
Send, 23456{enter}
Sleep %retardo%
Send, 9243CTS{enter}
Sleep %retardo%
Send, D{enter}
Sleep %retardo%
Send, 2400{enter}
Sleep %retardo%
Send, 54345{enter}
Sleep %retardo%
Send, 7658DVT{enter}
Sleep %retardo%
Send, D{enter}
Sleep %retardo%
Send, 1800{enter}
Sleep %retardo%
Send, 23456{enter}
Sleep %retardo%
Send, 4235KWZ{enter}
Sleep %retardo%
Send, G{enter}
Sleep %retardo%
Send, 1500{enter}
Sleep %retardo%
Send, 93456{enter}
Sleep %retardo%

Send, IJ765{enter}
Sleep %retardo%

Send, 2{enter}
Sleep %retardo%
Send, 5368FHL{enter}
Sleep %retardo%
Send, D{enter}
Sleep %retardo%
Send, 2200{enter}
Sleep %retardo%
Send, 87673{enter}
Sleep %retardo%
Send, 9987GJM{enter}
Sleep %retardo%
Send, G{enter}
Sleep %retardo%
Send, 2400{enter}
Sleep %retardo%
Send, 84765{enter}
Sleep %retardo%

Send, KV783{enter}
Sleep %retardo%

Send, 4{enter}
Sleep %retardo%
Send, 8593FBG{enter}
Sleep %retardo%
Send, G{enter}
Sleep %retardo%
Send, 2601{enter}
Sleep %retardo%
Send, 87678{enter}
Sleep %retardo%
Send, 1235GCH{enter}
Sleep %retardo%
Send, G{enter}
Sleep %retardo%
Send, 2400{enter}
Sleep %retardo%
Send, 56487{enter}
Sleep %retardo%
Send, 2314HDJ{enter}
Sleep %retardo%
Send, G{enter}
Sleep %retardo%
Send, 2200{enter}
Sleep %retardo%
Send, 74523{enter}
Sleep %retardo%
Send, 6478KFK{enter}
Sleep %retardo%
Send, D{enter}
Sleep %retardo%
Send, 2000{enter}
Sleep %retardo%
Send, 85653{enter}
Sleep %retardo%
Send, fin{enter}

return

^e::
Send, AB653{enter}
Sleep %retardo%

Send, 3{enter}
Sleep %retardo%
Send, 7646DKL{enter}
Sleep %retardo%
Send, G{enter}
Sleep %retardo%
Send, 1200{enter}
Sleep %retardo%
Send, 30000{enter}
Sleep %retardo%
Send, 6530CWS{enter}
Sleep %retardo%
Send, D{enter}
Sleep %retardo%
Send, 1400{enter}
Sleep %retardo%
Send, 40000{enter}
Sleep %retardo%
Send, 5246FRS{enter}
Sleep %retardo%
Send, D{enter}
Sleep %retardo%
Send, 2000{enter}
Sleep %retardo%
Send, 45700{enter}
Sleep %retardo%

Send, HB876{enter}
Sleep %retardo%

Send, 5{enter}
Sleep %retardo%
Send, 6547HRP{enter}
Sleep %retardo%
Send, G{enter}
Sleep %retardo%
Send, 2201{enter}
Sleep %retardo%
Send, 32402{enter}
Sleep %retardo%
Send, 3948BSR{enter}
Sleep %retardo%
Send, G{enter}
Sleep %retardo%
Send, 3000{enter}
Sleep %retardo%
Send, 23456{enter}
Sleep %retardo%
Send, 9243CTS{enter}
Sleep %retardo%
Send, D{enter}
Sleep %retardo%
Send, 2400{enter}
Sleep %retardo%
Send, 54345{enter}
Sleep %retardo%
Send, 7658DVT{enter}
Sleep %retardo%
Send, D{enter}
Sleep %retardo%
Send, 1800{enter}
Sleep %retardo%
Send, 23456{enter}
Sleep %retardo%
Send, 4235KWZ{enter}
Sleep %retardo%
Send, G{enter}
Sleep %retardo%
Send, 1500{enter}
Sleep %retardo%
Send, 93456{enter}
Sleep %retardo%

Send, IJ765{enter}
Sleep %retardo%

Send, 2{enter}
Sleep %retardo%
Send, 5368FHL{enter}
Sleep %retardo%
Send, D{enter}
Sleep %retardo%
Send, 2200{enter}
Sleep %retardo%
Send, 87673{enter}
Sleep %retardo%
Send, 9987GJM{enter}
Sleep %retardo%
Send, G{enter}
Sleep %retardo%
Send, 1600{enter}
Sleep %retardo%
Send, 84765{enter}
Sleep %retardo%

Send, KV783{enter}
Sleep %retardo%

Send, 4{enter}
Sleep %retardo%
Send, 8593FBG{enter}
Sleep %retardo%
Send, G{enter}
Sleep %retardo%
Send, 2600{enter}
Sleep %retardo%
Send, 87678{enter}
Sleep %retardo%
Send, 1235GCH{enter}
Sleep %retardo%
Send, G{enter}
Sleep %retardo%
Send, 2400{enter}
Sleep %retardo%
Send, 56487{enter}
Sleep %retardo%
Send, 2314HDJ{enter}
Sleep %retardo%
Send, G{enter}
Sleep %retardo%
Send, 2200{enter}
Sleep %retardo%
Send, 74523{enter}
Sleep %retardo%
Send, 6478KFK{enter}
Sleep %retardo%
Send, D{enter}
Sleep %retardo%
Send, 1000{enter}
Sleep %retardo%
Send, 85653{enter}
Sleep %retardo%
Send, fin{enter}